#ifndef ALIENWARS_SHADERS_H
#define ALIENWARS_SHADERS_H
/* WebGL2 / OpenGL 3.3 shaders. World-space materials preserve tile seams.
 * Keep the nonnegative vertex rank (uv.x) active in every pass: Raylib's
 * non-VAO DrawMesh path binds the texcoord attribute unconditionally. */
#ifdef PLATFORM_WEB
#define AW_GLSL "#version 300 es\nprecision highp float;\n"
#else
#define AW_GLSL "#version 330\nprecision highp float;\n"
#endif
#define AW_ENVIRONMENT_GRADE \
    "vec3 environmentGrade(vec3 c,float emission){float hi=max(c.r,max(c.g,c.b)),lo=min(c.r,min(c.g,c.b));float chroma=(hi-lo)/max(hi,.001);float saturation=mix(.82,.58,smoothstep(.08,.50,chroma));saturation=mix(saturation,.88,clamp(emission,0.0,1.0));vec3 linear=pow(max(c,vec3(0)),vec3(2.2));float luminance=dot(linear,vec3(.2126,.7152,.0722));return pow(mix(vec3(luminance),linear,saturation),vec3(1.0/2.2));}\n"

static const char *aw_vertex_shader = AW_GLSL
    "in vec3 vertexPosition;\n"
    "in vec3 vertexNormal;\n"
    "in vec2 vertexTexCoord;\n"
    "in vec4 vertexColor;\n"
    "uniform mat4 mvp;\n"
    "out vec3 position;\n"
    "out vec3 normal;\n"
    "out vec4 color;\n"
    "out vec2 uv;\n"
    "void main(){position=vertexPosition;normal=vertexNormal;color=vertexColor;uv=vertexTexCoord;gl_Position=mvp*vec4(vertexPosition,1.0);}\n"
;

static const char *aw_land_fragment = AW_GLSL
    "in vec3 position;in vec3 normal;in vec4 color;in vec2 uv;out vec4 finalColor;\n"
    "uniform float reveal;\n"
    "uniform vec3 cutEye,cutTarget,viewDirection;\n"
    "uniform int cutMode,tunnelView,renderPass,aoEnabled,detailEnabled;\n"
    "uniform mat4 lightVP;\n"
    "uniform sampler2D texture0,texture1,texture2;\n"
    "float hash(vec3 p){p=fract(p*0.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}\n"
    "float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+1.0),f.x),f.y),f.z);}\n"
    "float fbm(vec3 p){return noise(p)*0.55+noise(p*2.03)*0.27+noise(p*4.11)*0.13+noise(p*8.21)*0.05;}\n"
    "vec3 tone(vec3 c){c=max(c,vec3(0));return pow(clamp((c*(2.51*c+0.03))/(c*(2.43*c+0.59)+0.14),0.0,1.0),vec3(1.0/2.2));}\n"
    "\n"
    AW_ENVIRONMENT_GRADE
    /* World-space triplanar sampling handles vertical cliffs and cave ceilings.
     * Hardware mipmaps filter fine detail as its screen footprint shrinks. */
    "vec4 detailMap(vec3 p,vec3 w){return texture(texture2,p.yz)*w.x+texture(texture2,p.xz)*w.y+texture(texture2,p.xy)*w.z;}\n"
    "vec3 detailNormal(vec3 p,vec3 n,float height){vec3 dx=dFdx(p),dy=dFdy(p),r1=cross(dy,n),r2=cross(n,dx);float det=dot(dx,r1);vec3 gradient=(dFdx(height)*r1+dFdy(height)*r2)*sign(det)/max(abs(det),.00000001);return normalize(n-gradient); }\n"
    "float shadow(vec3 p,vec3 n){\n"
    " vec4 q=lightVP*vec4(p+n*0.055,1.0);vec3 s=q.xyz/q.w*0.5+0.5;\n"
    " if(any(lessThan(s,vec3(0)))||any(greaterThan(s,vec3(1))))return 1.0;\n"
    " float visibility=0.0;float bias=0.00012+0.00018*(1.0-max(dot(n,normalize(vec3(-.55,.85,-.40))),0.0));\n"
    " for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){\n"
    "  vec2 encoded=texture(texture1,s.xy+vec2(x,y)*1.35/2048.0).rg;float depth=encoded.r+encoded.g/255.0;\n"
    "  visibility+=s.z-bias<=depth?1.0:0.0;\n"
    " }return visibility/9.0;\n"
    "}\n"
    "void main(){\n"
    " if(uv.x>reveal)discard;\n"
    " if(renderPass==1&&position.y< -0.10)discard;\n"
    " if(tunnelView==1&&normal.y< -0.1)discard;\n"
    " if(cutMode==2&&position.y>cutTarget.y+1.5)discard;\n"
    " if(cutMode>0&&position.y>cutTarget.y+0.15){\n"
    "  vec3 ray=cutTarget-cutEye;float t=dot(position-cutEye,ray)/dot(ray,ray);\n"
    "  float r=length(position-(cutEye+clamp(t,0.0,1.0)*ray));\n"
    "  if(t>0.0&&t<1.0&&r<3.6){float screen=fract(dot(floor(gl_FragCoord.xy),vec2(0.5,0.25)));if(r<2.7||screen>smoothstep(2.7,3.6,r))discard;}\n"
    " }\n"
    " vec3 n=normalize(normal);if(!gl_FrontFacing)n=-n;\n"
    " vec3 sun=normalize(vec3(-0.55,0.85,-0.40)),v=normalize(viewDirection);\n"
    " vec3 albedo=color.rgb;float roughness=0.88,metal=0.0,emission=0.0;\n"
    " float kind=uv.y;\n"
    " float coarse=fbm(position*.55),fine=noise(position*12.0);\n"
    " if(kind<0.5||kind>9.5){\n"
    "  vec4 coverage=kind>9.5&&kind<11.5?texture(texture0,(position.xz*.5+.5)/65.0):vec4(0);\n"
    "  coverage/=max(1.0,dot(coverage,vec4(1)));\n"
    "  float stone=max(1.0-smoothstep(.45,.83,normal.y),1.0-dot(coverage,vec4(1)));\n"
    "  if(kind<.5||kind>11.5)stone=1.0;\n"
    "  float grass=coverage.r*(1.0-stone),snow=coverage.b*(1.0-stone),road=coverage.a*(1.0-stone);\n"
    "  vec3 rock=mix(vec3(.30,.30,.28),vec3(.46,.44,.40),coarse);\n"
    "  float rockTint=kind>11.5?1.0-smoothstep(.45,.83,normal.y):stone;\n"
    "  albedo=mix(albedo,rock,rockTint*.92);\n"
    "  albedo*=.94+coarse*.10;\n"
    "  float wet=(1.0-smoothstep(-.05,1.1,position.y))*(1.0-stone*.4);\n"
    "  albedo*=1.0-wet*.12;roughness=mix(.94,.58,wet);\n"
    "  if(detailEnabled>0){\n"
    "   vec3 weights=pow(abs(normal),vec3(4));weights/=max(dot(weights,vec3(1)),.0001);\n"
    "   vec4 d=detailMap(position*.23,weights),micro=detailMap(position.zxy*.51+vec3(.37,.71,.19),weights.zxy);\n"
    "   vec4 surface=d*.74+micro*.26;\n"
    "   float grain=mix(surface.r,surface.b,grass);grain=mix(grain,surface.a,snow);grain=mix(grain,surface.g,stone);\n"
    "   float detailHeight=(grain-.5)*mix(.075,.018,snow)*mix(1.0,.45,road);\n"
    "   n=detailNormal(position,n,detailHeight);\n"
    "   float contrast=mix(.58,.22,snow)*mix(1.0,.5,road);\n"
    "   albedo*=1.0+(grain-.5)*contrast;\n"
    "   vec3 litter=vec3(.37,.35,.28);\n"
    "   albedo=mix(albedo,litter,grass*(1.0-smoothstep(.31,.48,surface.b))*.32);\n"
    "   roughness=clamp(roughness+(micro.r-.5)*.14-stone*.035,.48,.99);\n"
    "  }\n"
    " }\n"
    " if(kind>2.5&&kind<3.5){albedo*=.87+fine*.18;roughness=.80;}\n"
    " if(kind>3.5&&kind<4.5){float bark=fbm(position*vec3(18,.8,18));albedo*=.78+.34*bark;}\n"
    " if(kind>4.5&&kind<5.5){metal=.55;roughness=.46;albedo*=.91+fine*.13;}\n"
    " if(kind>5.5&&kind<6.5){metal=.75;roughness=.22;}\n"
    " if(kind>1.5&&kind<2.5)emission=.65;\n"
    " vec3 linear=pow(albedo,vec3(2.2));\n"
    " float nl=max(dot(n,sun),0.0),nv=max(dot(n,v),.01);\n"
    " vec3 h=normalize(sun+v);float nh=max(dot(n,h),0.0),vh=max(dot(v,h),0.0);\n"
    " float a=roughness*roughness,a2=a*a,den=nh*nh*(a2-1.0)+1.0;\n"
    " float D=a2/(3.14159*den*den+0.0001),k=(roughness+1.0)*(roughness+1.0)/8.0;\n"
    " float G=nl/(nl*(1.0-k)+k)*nv/(nv*(1.0-k)+k);\n"
    " vec3 f0=mix(vec3(.035),linear,metal),F=f0+(1.0-f0)*pow(1.0-vh,5.0);\n"
    /* Camera cutaways only hide fragments. Keep the intact world's sunlight
     * occlusion so revealing a scout cannot switch off every terrain/prop shadow. */
    " float visibility=tunnelView>0||reveal<4095.0?1.0:shadow(position,n);\n"
    " float ao=aoEnabled>0?clamp(color.a,0.0,1.0):1.0;\n"
    /* Broad overcast fill carries the scene. Weak key light and restrained AO
     * preserve shape without deep black cliffs or high-contrast prop shadows. */
    " vec3 sky=mix(vec3(.40,.45,.49),vec3(.52,.56,.58),n.y*.5+.5);\n"
    " vec3 ambient=linear*sky*mix(.68,1.0,ao);\n"
    " vec3 diffuse=linear*(1.0-metal)*nl;\n"
    " vec3 spec=D*G*F/max(4.0*nl*nv,.001)*nl;\n"
    " vec3 lit=ambient+(diffuse+spec*.55)*vec3(.48,.46,.42)*mix(.40,1.0,visibility);\n"
    " if(kind>2.5&&kind<3.5)lit+=linear*vec3(.16,.20,.09)*pow(max(dot(-n,sun),0.0),2.0);\n"
    " lit*=.62;lit+=linear*emission;\n"
    /* Guides and navigation overlays keep a stable, bright response rather
     * than inheriting the terrain's subdued lighting. Scout/UI use other passes. */
    " if(kind>1.5&&kind<2.5)lit=linear*(1.0+emission);\n"
    " vec3 result=tone(lit);\n"
    " float fog=smoothstep(72.0,155.0,length(position.xz-vec2(64)));\n"
    " result=mix(result,vec3(.068,.104,.125),fog*.72);\n"
    " if(kind<1.5||kind>2.5)result=environmentGrade(result,emission);\n"
    " finalColor=vec4(result,kind>1.5&&kind<2.5?color.a:1.0);\n"
    "}\n"
;

static const char *aw_water_fragment = AW_GLSL
    "in vec3 position;in vec3 normal;in vec4 color;in vec2 uv;out vec4 finalColor;\n"
    "uniform float time;uniform vec3 viewDirection;\n"
    "uniform mat4 reflectionVP;\n"
    "uniform sampler2D texture0,texture1;\n"
    "float hash(vec3 p){p=fract(p*0.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}\n"
    "float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+1.0),f.x),f.y),f.z);}\n"
    "float fbm(vec3 p){return noise(p)*0.55+noise(p*2.03)*0.27+noise(p*4.11)*0.13+noise(p*8.21)*0.05;}\n"
    "vec3 tone(vec3 c){c=max(c,vec3(0));return pow(clamp((c*(2.51*c+0.03))/(c*(2.43*c+0.59)+0.14),0.0,1.0),vec3(1.0/2.2));}\n"
    "\n"
    AW_ENVIRONMENT_GRADE
    "void main(){\n"
    " if(uv.x<0.0)discard;vec2 p=position.xz;vec4 coast=texture(texture0,(p+32.0)/192.0);\n"
    " if(coast.a<.5)discard;\n"
    " float dist=coast.r*12.0;\n"
    " vec2 d1=normalize(vec2(.8,.35)),d2=normalize(vec2(-.35,.91)),d3=normalize(vec2(.6,-.74));\n"
    " float phase1=dot(p,d1)*1.12+time*.73,phase2=dot(p,d2)*2.5-time*1.17,phase3=dot(p,d3)*5.4+time*1.55;\n"
    " vec2 slope=d1*cos(phase1)*.065+d2*cos(phase2)*.044+d3*cos(phase3)*.022;\n"
    " slope+=vec2(fbm(vec3(p*.72,time*.13)),fbm(vec3(p.yx*.87,time*.17)))-.5;\n"
    " slope*=.23;\n"
    " vec3 n=normalize(vec3(-slope.x,1.0,-slope.y)),v=normalize(viewDirection),sun=normalize(vec3(-.55,.85,-.40));\n"
    " float fresnel=.035+.965*pow(1.0-max(dot(n,v),0.0),5.0);\n"
    " vec4 q=reflectionVP*vec4(position,1);vec2 r=q.xy/q.w*.5+.5;\n"
    " r+=slope*.034*clamp(dist*.45,0.0,1.0);\n"
    " vec3 reflected=texture(texture1,clamp(r,.002,.998)).rgb;\n"
    " vec3 sky=vec3(.39,.48,.53);reflected=mix(reflected,sky,.13);\n"
    " float depth=1.0-exp(-dist*.24);\n"
    " vec3 body=mix(vec3(.14,.28,.265),vec3(.022,.082,.11),depth);\n"
    " float caustic=pow(1.0-abs(sin(phase2+sin(phase1)*.9)),9.0);\n"
    " body+=vec3(.20,.26,.19)*caustic*.08*(1.0-depth);\n"
    " vec3 base=mix(body,reflected,clamp(.2+fresnel*.72,.0,.83));\n"
    " vec3 h=normalize(v+sun);float spec=pow(max(dot(n,h),0.0),180.0);\n"
    " base+=vec3(1.0,.91,.70)*spec*.04;\n"
    " float surge=.5+.5*sin(dist*4.4-time*1.35+fbm(vec3(p*.9,0))*3.0);\n"
    " float foam=(1.0-smoothstep(.08,.85,dist))*smoothstep(.54,.86,surge)*smoothstep(.25,.6,noise(vec3(p*4.5,time*.15)));\n"
    " base=mix(base,vec3(.66,.73,.69),foam*.28);\n"
    " base*=.80;float edge=smoothstep(104.0,165.0,length(p-vec2(64.0)));\n"
    " finalColor=vec4(environmentGrade(mix(base,vec3(.027,.049,.064),edge),0.0),1.0);\n"
    "}\n"
;

static const char *aw_shadow_fragment = AW_GLSL
    "in vec3 position;in vec3 normal;in vec4 color;in vec2 uv;out vec4 finalColor;\n"
    "void main(){if(uv.x<0.0)discard;float depth=min(gl_FragCoord.z,.99999);vec2 encoded=fract(depth*vec2(1.0,255.0));encoded.x-=encoded.y/255.0;finalColor=vec4(encoded,0.0,1.0);}\n"
;

#endif
